spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/distanceStudyPlatform?useUnicode=true&serverTimezone=UTC}
  profiles:
    active: disable-security
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/liquibase/changelog/db.changelog-master.xml
    enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false